version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: GithubPackageCrawler
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: GithubPackageCrawlerDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
